### ISSUE TITLE
Is there a way to "debounce" the button pushes on a two-encoder setup?

### ISSUE THREAD

**Issue by thundernixon** [andyclymer/minikbd#6]
I'm using the two-mode setup for the two-encoder, and I love it!

One mode uses the music control configuration: play/pause, prev/next, & volume.

The other mode is setup to control video via the fantastic [Video Speed Controller](https://github.com/igrigorik/videospeed) chrome extension: play/pause, faster/slower skip-forward/backward.

However, in both cases, I have some problems around play/pause input, which I have attached to an encoder press. My best guess is that this is due to a lack of [debouncing](https://www.maximintegrated.com/en/glossary/definitions.mvp/term/debounce/gpk/82) on the button press – so each press is actually captured as many presses, and this confuses most play/pause controls.

I wanted to test/show this theory, so I made [a Codepen that responds to keypresses](https://codepen.io/thundernixon/pen/WLJwBd). In the gif below, I touch my real spacebar three times, and then I press the MiniKbd encoder a couple of times. It shows that the MiniKbd input is actually registered as many key presses, which is probably what is messing this up for YouTube controls, etc, currently.

![kapture 2019-01-06 at 13 28 21](https://user-images.githubusercontent.com/7355414/50740067-3e18a280-11b7-11e9-8407-dda4619c537b.gif)

Is there any good way to debounce key input from these controllers? If so, it would make the button presses quite a bit more useful. Thanks for any tips!

**Comment by andyclymer** [comment]
Yeah, if you need to denounce the button you can see a lazy way that I did it in this example with the fastTurn function:

https://github.com/andyclymer/minikbd/blob/master/Software/TwoEncoder-VolumeControl/main.py

I say it’s lazy because it limits all button presses and not just a repeated press on the same button. But maybe this is a good starting point?

**Comment by thundernixon** [comment]
Sorry it took me so long to try this and report back. It works perfectly!

I've recorded my current setup (including this code) at https://gist.github.com/thundernixon/6b77fef43f57a814e21542ba8de1af1b
