### ISSUE TITLE
Ponoko rejects the Ponoko files

### ISSUE THREAD

**Issue by timkingman** [andyclymer/minikbd#7]
I tried to upload Ponoko-MiniKbd-SixKeys.eps to Ponoko, and I got a "Blue Alert" error:
<img width="464" alt="screen shot 2019-01-09 at 8 25 55 am" src="https://user-images.githubusercontent.com/1649058/50902314-8a96f480-13e8-11e9-80f2-d56b8f74a333.png">

"Fix this right now" links to https://ponoko.zendesk.com/hc/en-us/community/posts/210090228-File-won-t-upload-says-Oops-Blue-Alert-

I'm not in enough of a hurry to ask Ponoko support for help, but my soldering buddy might have Illustrator, so I'll see if I can figure out a fix and submit a PR.

**Comment by andyclymer** [comment]
Ah! That must be my mistake, thanks for bringing it to my attention. I’m traveling right now and am away from the computer for a little while, but if you’re able to change the color and submit a PR that would be great.

The “AllThree” file should work, I had a couple copies made of that one from Ponoko to test out the service.

**Comment by JoshApos** [comment]
Just commenting to confirm that the 'AllThree' file worked as of August '19.

I won't receive the pieces being cut for another few weeks, but I received confirmation that the files were accepted and the order was being made.

**Comment by andyclymer** [comment]
Hi @timkingman and @JoshApos ,

My mistake for missing this issue when it was posted months ago, but it looks like there was a problem with two of the files. I fixed them and can confirm that all of the Ponoko laser files do properly upload now. Thanks for calling this to my attention!
