### ISSUE TITLE
CircuitPython code crashes on newest versions of CP and hid library

### ISSUE THREAD

**Issue by FoamyGuy** [andyclymer/minikbd#9]
```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
TypeError: function takes 2 positional arguments but 1 were given
```

This error is due to a slight change in the `adafruit_hid` library, it now needs to be passed a parameter in it's constructor.

**Comment by andyclymer** [comment]
Thank you for these! I'm traveling right now and don't have a MiniKbd on hand (if you can believe it), but the changes look good. I'll merge and leave a note that the example scripts are for CircuitPython version 4 and above. Thank you again!
